POST  http://localhost:3000/api/roominfo
content-type: application/json

{
   "roomId": "asdasdasdasdsa",
   "roomName": "asdasdasdasd",
   "isPrivate": true,
   "userName": "2222112222222"
}

###
GET   http://localhost:3000/api/roominfo?roomId=-tMT62vj0OgrW3PFghzG2